---
mapping:
  # For list of keys, look at kb4gc/keyboard.py

  # Right side buttons
  a: U
  b: I
  x: O
  y: P

  # Bumpers
  l: R
  r: 7
  z: 8

  # Control Stick
  up: W
  left: A
  down: S
  right: D

  # Modifiers
  mod1: SPACE
  mod2: LEFTSHIFT

  # C Stick
  cup: M
  cleft: N
  cdown: COMMA
  cright: DOT

  # D Pad
  dleft: Z
  dup: X
  ddown: C
  dright: V

  # Start button
  start: ENTER

  # Switch button
  switch_: ESC

values:
  # set values for various angles
  x1v: 44
  x2v: 53
  x3v: 73

  y1v: 37
  y2v: 55
  y3v: 73

hardware:
  # Which stream is the keyboard
  keyboard: /dev/input/event0

  # Which pin the gamecube output should be
  gc_output: 8

wiring:
  # This maps Pi GPIO to arduino inputs
  4: 22
  5: 24
  6: 26
  7: 28
  8: 30
  9: 31
  10: 34
  11: 35
  12: 38
  13: 39
  14: 40
  15: 41
  16: 44
  17: 45
  18: 46
  19: 47
  20: 48
  21: 49
  22: 50
  23: 51
  24: 12
