---
mapping:
  # For list of keys, look at kb4gc/keyboard.py

  # Right side buttons
  a: U
  b: I
  x: O
  y: P

  # Bumpers
  l: R
  r: '7'
  z: '8'
  rlight: '9'

  # Control Stick
  up: W
  left: A
  down: S
  right: D

  # Modifiers
  mod1: SPACE
  mod2: LEFTSHIFT

  # C Stick
  cup: M
  cleft: N
  cdown: COMMA
  cright: DOT

  # D Pad
  x1: Z
  y1: X
  x2: C
  y2: V

  # Start button
  start: ENTER

  # Switch button
  switch_: ESC

values:
  # set values for various angles
  x1v: 44
  x2v: 53
  x3v: 73

  y1v: 37
  y2v: 55
  y3v: 73

hardware:
  # Which pin the gamecube output should be
  gc_output: 8
